### PR TITLE
Comment typo: nore ➡️ node

### PR DESCRIPTION
**Pull request by fasterthanlime**
🐿️

### CODE REVIEW

**Comment by examknow** [comment]
please PR this into the `master` branch

**Comment by kaniini** [comment]
The module in question doesn't exist in `master` anymore...

**Comment by alyx** [comment]
> The module in question doesn't exist in `master` anymore...

Clearly this just means we should re-add it so it can be fixed in master. ⭐ 

But anyways, thanks for the fix!

**Comment by fasterthanlime** [comment]
> The module in question doesn't exist in `master` anymore...

Uh oh, sorry! Someone linked to a specific commit on Twitter and I used GitHub's edit functionality on mobile, I didn't even check if it was still in the default branch 🙃

**Comment by alyx** [comment]
Lol no worries :D

**Pull request merged**
