### PR TITLE
Implement a unified message digest API

### PR DESCRIPTION
**Pull request by aaronmdjones**

### CODE REVIEW

**Comment by aaronmdjones** [comment]
The only part of this that has not been tested so far is SASL SCRAM-SHA logins with the ARM mbedTLS frontend; everything else is feature-complete and works -- I will be testing mbedTLS on my own testnet later today.

**Comment by aaronmdjones** [comment]
Can anyone think of any other common cryptographic libraries that I can add support for?

The following are required:

1. Supports MD5, SHA1, SHA2-256 and SHA2-512
2. Is not an experience in hell to write code for

The following are not required, but are considered bonuses:

3. Avoids dynamic memory allocation
4. Supports HMAC
5. Supports PBKDF2-HMAC

The only one that comes to mind is libgcrypt, but that may violate required item 2. At least, when I glanced at the man pages when I was writing this, I didn't like what I saw.

**Comment by grawity** [comment]
[nettle](https://www.lysator.liu.se/~nisse/nettle/nettle.html)? (It's the underlying crypto library of GnuTLS so relatively common.) No personal experience with it though.

**Comment by aaronmdjones** [comment]
How on earth did I forget about nettle ...

I'll have a look at that tomorrow. Thanks.

**Comment by aaronmdjones** [comment]
Apologies, my trackpad hit the wrong button.

**Comment by aaronmdjones** [comment]
Another issue is that at the moment the configure script will decide to use ARM mbedTLS as the digest frontend if the libmbedcrypto library is found and is usable, but the necessary headers may not be available.

I will extend the detection to include headers tomorrow too, like it currently does for OpenSSL.

**Comment by aaronmdjones** [comment]
All of the digest frontends pass our integrated test suite.

**Comment by aaronmdjones** [comment]
I do believe I am done unless anything is raised here.

**Comment by aaronmdjones** [comment]
Note that `modules/crypto/posix` has deliberately not been modified because I'd rather rewrite it (#603).

**Pull request merged**
