### PR TITLE
Add +e and change "SaslServ"

### PR DESCRIPTION
**Pull request by Spydar007**
Add +e to chanserv{} templates and founder_flags, and change SaslServ to SASLServ as per acronym capitalization rules.

### CODE REVIEW

**Comment by ilbelkyr** [comment]
I feel like these changes should be in two separate commits; they seem quite unrelated.

**Comment by jillest** [comment]
I like the templates part but not the saslserv renaming part.

**Comment by Mikaela** [comment]
:+1: to ibelkyr and I don't think SaslServ should be renamed. It would become different from NickServ and other \*Servs and everyone is used to it being SaslServ, but this is just how I feel.

**Comment by kaniini** [comment]
:-1: on the SaslServ renaming.  Patch rejected.

**Pull request closed without merging**
