### PR TITLE
NickServ REGAIN: log in before changing nick

### PR DESCRIPTION
**Pull request by ddevault**
This addresses a race condition where the user is "banned" on a channel
because all unregistered users are banned, preventing them from changing
their nick.

---

This is an alternate take on #711. I maintain that this is the wrong fix, but it's your project, so here you go.

### CODE REVIEW

**Comment by kaniini** [comment]
looks good to me

**Comment by dwfreed** [comment]
The maxlogins check needs to be moved as well, I think?

**Comment by alyx** [comment]
looks good to me, sorry for this being delayed.

**Comment by ddevault** [comment]
Thanks.

**Pull request merged**
